version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - exc01-db:/var/lib/postgresql/data
  backend:
    build:
      context: backend/.
    volumes:
      - ./backend:/backend
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - db
    ports:
      - '4000:4000'
    working_dir: /backend

volumes:
  exc01-db:
